/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Reset all the layers/animations/etc. */
typedef struct _Reset { 
    char dummy_field;
} Reset;

/* Represents */
typedef struct _Pulse { 
    /* The area that this effect will be played on. */
    bool has_universe;
    int32_t universe; 
    /* The layer that perform this animation. */
    bool has_layer;
    int32_t layer; 
    /* The unique key for this animation. */
    bool has_key;
    int32_t key; 
    /* the color (RGB) to show. */
    bool has_color;
    int32_t color; 
    /* Number of ticks to slowly fade into the max value of the pulse. */
    bool has_fade_in_ticks;
    int32_t fade_in_ticks; 
    /* The total number of ticks to display the full pulse. */
    bool has_duration_ticks;
    int32_t duration_ticks; 
    /* Number of ticks to slowly fade out to nothing. */
    bool has_fade_out_ticks;
    int32_t fade_out_ticks; 
} Pulse;

typedef struct _HypnoMessage { 
    pb_size_t which_message;
    union {
        Reset reset;
        Pulse pulse;
    } message; 
} HypnoMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HypnoMessage_init_default                {0, {Reset_init_default}}
#define Reset_init_default                       {0}
#define Pulse_init_default                       {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define HypnoMessage_init_zero                   {0, {Reset_init_zero}}
#define Reset_init_zero                          {0}
#define Pulse_init_zero                          {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Pulse_universe_tag                       1
#define Pulse_layer_tag                          2
#define Pulse_key_tag                            3
#define Pulse_color_tag                          4
#define Pulse_fade_in_ticks_tag                  5
#define Pulse_duration_ticks_tag                 6
#define Pulse_fade_out_ticks_tag                 7
#define HypnoMessage_reset_tag                   1
#define HypnoMessage_pulse_tag                   2

/* Struct field encoding specification for nanopb */
#define HypnoMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,reset,message.reset),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,pulse,message.pulse),   2)
#define HypnoMessage_CALLBACK NULL
#define HypnoMessage_DEFAULT NULL
#define HypnoMessage_message_reset_MSGTYPE Reset
#define HypnoMessage_message_pulse_MSGTYPE Pulse

#define Reset_FIELDLIST(X, a) \

#define Reset_CALLBACK NULL
#define Reset_DEFAULT NULL

#define Pulse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    universe,          1) \
X(a, STATIC,   OPTIONAL, INT32,    layer,             2) \
X(a, STATIC,   OPTIONAL, INT32,    key,               3) \
X(a, STATIC,   OPTIONAL, INT32,    color,             4) \
X(a, STATIC,   OPTIONAL, INT32,    fade_in_ticks,     5) \
X(a, STATIC,   OPTIONAL, INT32,    duration_ticks,    6) \
X(a, STATIC,   OPTIONAL, INT32,    fade_out_ticks,    7)
#define Pulse_CALLBACK NULL
#define Pulse_DEFAULT NULL

extern const pb_msgdesc_t HypnoMessage_msg;
extern const pb_msgdesc_t Reset_msg;
extern const pb_msgdesc_t Pulse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HypnoMessage_fields &HypnoMessage_msg
#define Reset_fields &Reset_msg
#define Pulse_fields &Pulse_msg

/* Maximum encoded size of messages (where known) */
#define HypnoMessage_size                        79
#define Pulse_size                               77
#define Reset_size                               0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
