/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HypnoMessage, HypnoMessage, AUTO)


PB_BIND(Prime, Prime, AUTO)


PB_BIND(Reset, Reset, AUTO)


PB_BIND(Universe, Universe, AUTO)


PB_BIND(UniverseConfiguration, UniverseConfiguration, AUTO)


PB_BIND(LayerConfiguration, LayerConfiguration, AUTO)


PB_BIND(Pulse, Pulse, AUTO)




